FN CETAK_DESKRIPSI(ITEM: &IMPL DESKRIPSI) {
PRINTLN!("{}", ITEM.DESKRIPSI());

}
FN MAIN() {
LET BUKU = BUKU {
JUDUL: STRING::FROM("Pemrograman Rust"),
PENULIS: STRING::FROM("John Doe"),
};

LET FILM = FILM {
JUDUL: STRING::FROM("Rust: The Movie"),
SUTRADARA: STRING::FROM("Jane Smith"),
};

CETAK_DESKRIPSI(&BUKU);

CETAK_DESKRIPSI(&FILM);

}